package org.softhk.gameout.utils

val BASE_URL:String = "https://api.rawg.io/api/"
val GET_DATA = "--GETDATA--"

object SharedPreferenceItem{
    val SHARED_PREFERENCES_KEY:String = "GAMEOUT_KEY"
    val SHARED_PREFERECES_ELEMENT_TO_SHOW_RECYCLER = "ELEMENT_TO_SHOW"
    val SHARED_PREFERENCES_SPINNER_POSITION = "SPINNER_POSITION"
    val SHARED_PREFERENCES_SHOW_DEFAULT_ITEM_RECYCLERVIEW = 5
    val SHARED_PREFERENCES_SHOW_LAYOUTMANAGER_RECYCLER_VIEW_KEY = "SHOW_LAYOUT_MANAGER"
    val SHARED_PREFERENCES_LINEARLAYOUT = "LINEAR_LAYOUT"
    val SHARED_PREFERENCES_GRIDLAYOUT = "GRID_LAYOUT"
    var listOfItemToShowRecyclerView = arrayListOf<Int>(5,10,20,30,40)
}

enum class LayoutManagerType{
    LINEAR,GRID
}
